### ISSUE TITLE
if set textwidth=80, it will not align right

### ISSUE THREAD

**Issue by Freed-Wu** [dbmrq/vim-chalk#2]
if set textwidth=80, it will not align right. So I must set textwidth=0 before
use this plugin. Can it be solved by a better method?

```
function! init#ChalkUp_v() "{{{
	let l:textwidth = &textwidth
	setlocal textwidth =0
	'<, '>call chalk#makeFold('')
	let &textwidth = l:textwidth
endfunction "}}}
vnoremap zf :<C-U>call init#ChalkUp_v()<CR>
```

**Comment by dbmrq** [comment]
Mm, what do you mean "it will not align right"?

I'm pretty busy at the moment, but I'll try to look into it when I have the time.
